engines:
  eslint:
    enabled: true
    channel: "eslint-3"
    config: .eslintrc
   checks:
      camelcase:
        enabled: false
      arrow-parens :
        enabled: false
  duplication:
    enabled: false
    config:
      languages:
      - javascript
  fixme:
      enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths:
- data/*
- example/*.json
- example/*.json.example
- res/*