engines:
  eslint:
    enabled: true
    config: .eslintrc
  duplication:
    enabled: false
    config:
      languages:
      - javascript
  fixme:
      enabled: true
checks:
  return-statements:
    enabled: false
  method-complexity:
    enabled: false
  method-lines:
    enabled: false
  file-lines:
    enabled: false
  similar-code:
    enabled: false
ratings:
  paths:
  - "**.js"
exclude_paths:
- data/*
- assets/*