sudo: required
dist: trusty
language: node_js
node_js:
  - "6.1"
  - "6.6"
install:
- npm -g install -S
- npm -v
- mkdir out
- npm install -g babel-cli
- npm install babel-preset-es2015 --save
- npm install -g gulp-cli gulp-babel 
- npm install gulp
script :
- babel src --no-comments --minified -D -d out
- gulp build