sudo: required
dist: trusty
language: node_js
node_js:
  - "6.9"
  - "7.1"
install:
- npm -g install -S
- npm -v
- mkdir out
- npm install -g eslint
- npm install -g babel-cli
- npm install  babel-preset-latest --save
- npm install -g gulp-cli gulp-babel 
- npm install gulp gulp-babel --save
script :
- eslint ./src/commands
- babel src --no-comments --minified -D -d out

