sudo: required
dist: trusty
addons:
  apt:
    packages:
       - babel
       - openbabel
language: node_js
node_js:
  - "6"
  - "6.1"
install:
- npm -g install
- npm -v
- babel -v
- mkdir bin
script :
- npm build