sudo: required
dist: trusty
language: node_js
node_js:
  - "6.1"
  - "6.6"
install:
- npm -g install -S
- npm -v
- mkdir out
- npm install -g babel-cli
- npm install -g babel-preset-es2015
script :
- babel src -D -d out