version: 2
jobs:
  build:
    docker:
      - image: node:7.4.0
    working_directory: src
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install && sudo apt install docker docker.io
      - run:
          name: Docker Build
          command: docker build -f Dockerfile -t Clara:continous .