version: 2
jobs:
  build:
    docker:
      - image: library/node:8.4.0-wheezy
    working_directory: src
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Resolve Dependencies
          command: |
          npm i --save
      - run:
          name: ESLint
          command: eslint
