version: 2
notify: 
   webhooks:
     - url: https://discordapp.com/api/webhooks/294663888493084673/YIM9t7gK8vSZrE3HqnlKQNDi8p9XM1tyOlcT9T39MMBLc57GuoK53yxHVKILNKHE-Uhu/circle
jobs:
  build:
    docker:
      - image: node:7.4.0
    working_directory: src
    steps:
      - checkout
      - run:
          name: Install Docker client
        command: |
          set -x
          curl -L -o /tmp/docker.tgz https://get.docker.com/builds/Linux/x86_64/docker-1.12.3.tgz
          tar -xz -C /tmp -f /tmp/docker.tgz
          mv /tmp/docker/docker* /usr/bin/

          curl -L "https://github.com/docker/compose/releases/download/1.9.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/bin/docker-compose
          chmod +x  /usr/bin/docker-compose
          
      - type: setup-docker-engine
      - type: shell
        name: Verify Docker Works
        command: |
          docker --version
          docker run hello-world
          
      - run:
          name: Install Dependencies
          command: npm i -S
      - run:
          name: Docker Build
          command: docker build -f Dockerfile -t clara:continous .