version: 2
jobs:
  build:
    working_directory: src
    steps:
      - checkout
      - run:
          name: "Update npm"
          command: "sudo npm install -g npm@latest"
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: "Install deps"
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
  lint:
    steps:
      - checkout
      - run:
          name: "Run ESLint"
          command: npm run lint

workflows:
  version: 2
  build_and_lint:
    jobs:
      - build
      - test:
          - requires:
              - build

notify:
  webhooks:
    - url: https://claraio-circledisc.herokuapp.com/hooks/circleci
